language: perl
perl:
  - "5.24-shrplib"
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
apt:
  update: true
  packages:
    #- bioperl
    - sqlite3
    - libsqlite3-dev
    - libberkeleydb-perl
    - libcdb-file-perl
before_install:
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  #- sudo apt-get update -y
  #- sudo apt-get install bioperl sqlite3 libsqlite3-dev
  # bootstrap modules needed to manipulate dist
  #- "yes no | cpanm --force --notest Bio::Perl"
  #- cpanm -v -L . DBD::SQLite
  #- "yes no | cpanm --force --notest DBI"
  #- wget https://github.com/marbl/Mash/releases/download/v1.1.1/mash-Linux64-v1.1.1.tar.gz
  #- tar zxvf mash-Linux64-v1.1.1.tar.gz
  - wget https://github.com/marbl/Mash/releases/download/v2.2/mash-Linux64-v2.2.tar
  - tar xvf mash-Linux64-v2.2.tar
  - git clone https://github.com/khowe/quicktree.git
  - make -C quicktree
install:
  - export PATH=$PATH:$HOME/bin
  - export PERL5LIB=$PERL5LIB:$(pwd)/lib/perl5
  - export PERL5LIB=$PERL5LIB:$HOME/perl5:$HOME/perl5/lib/perl5
before_script:
  - ls -F # if this test fails, just be sure what the directory is
  - pwd; pwd -P
  - PATH=$PATH:./mash-Linux64-v2.2
  - export PATH=$PATH:./quicktree
script:
  #- cpanm -l . --notest --force -v Bio::Tree::Statistics Bio::Matrix::IO Bio::Tree::DistanceFactory
  #- find . -type f -name IO.pm || true
  #- find . -type f -name DistanceFactory.pm || true
  - cpanm --notest --force -l . CDRAUG/BioPerl-1.7.4.tar.gz
  - cpanm --installdeps --notest .
  - perl Makefile.PL 
  - perl bin/mashtree -h 2>&1 | grep .
  - perl bin/mashtree --help 2>&1 | grep .
  - make test

